%% main.m
% Fiscal Revenue and Public Debt Visualization
%
% This script:
%   1. Imports the Excel dataset.
%   2. Generates Figures 1–9.
%   3. Saves all figures as PNG files.
%
% Required files:
%   import_data.m
%   plot_line_chart.m
%   plot_subplot_chart.m
%   plot_bar_chart.m
%   hw1_data_matlab.xlsx

clear;
clc;
close all;

%% Import Data

filename = 'hw1_data_matlab.xlsx';

data = import_data(filename);

disp('Data imported successfully.');
disp(['Year range: ', num2str(min(data.year)), ...
      ' - ', num2str(max(data.year))]);


%% Figure 1
%  Annual Public Debt Issuance vs. Tax Revenue

plot_line_chart( ...
    data.year, ...
    [data.ann_pb_issu, data.sum_tax], ...
    {'Annual Public Debt Issuance', ...
     'Total Tax Revenue'}, ...
    'Annual Public Debt Issuance and Tax Revenue', ...
    'Ratio(%)', ...
    fullfile('figures', 'Figure1.png'));


%% Figure 2
%  Treasury Issuance: Total, Domestic, and Foreign

plot_line_chart( ...
    data.year, ...
    [data.ann_treasury_issu, ...
     data.ann_treasury_issu_d, ...
     data.ann_treasury_issu_e], ...
    {'Total Treasury Issuance', ...
     'Domestic Treasury Issuance', ...
     'Foreign Treasury Issuance'}, ...
    'Annual Treasury Issuance', ...
    'Ratio(%)', ...
    fullfile('figures', 'Figure2.png'));


%% Figure 3
%  Domestic vs. Foreign Treasury Issuance

plot_line_chart( ...
    data.year, ...
    [data.ann_treasury_issu_d, ...
     data.ann_treasury_issu_e], ...
    {'Domestic Treasury Issuance', ...
     'Foreign Treasury Issuance'}, ...
    'Domestic and Foreign Treasury Issuance', ...
    'Ratio(%)', ...
    fullfile('figures', 'Figure3.png'));


%% Figure 4
%  Major Tax Revenue Categories
%  2 x 3 Subplots

plot_subplot( ...
    data.year, ...
    [data.d_vat, ...
     data.d_ct, ...
     data.vatct_import, ...
     data.rbt_export, ...
     data.cit, ...
     data.iit], ...
    {'Domestic VAT', ...
     'Domestic Consumption Tax', ...
     'Import VAT and Consumption Tax', ...
     'Export Tax Refund', ...
     'Corporate Income Tax', ...
     'Individual Income Tax'}, ...
    [2, 3], ...
    'Major Tax Revenue Categories', ...
    'Ratio(%)', ...
    fullfile('figures', 'Figure4.png'));


%% Figure 5
%  Other Tax Revenue Categories
%  2 x 3 Subplots

plot_subplot( ...
    data.year, ...
    [data.rt, ...
     data.umct, ...
     data.stampt, ...
     data.tt, ...
     data.vpt, ...
     data.tariff], ...
    {'Resource Tax', ...
     'Urban Maintenance and Construction Tax', ...
     'Stamp Tax', ...
     'Tonnage Tax', ...
     'Vehicle Purchase Tax', ...
     'Tariff'}, ...
    [2, 3], ...
    'Other Tax Revenue Categories', ...
    'Ratio(%)', ...
    fullfile('figures', 'Figure5.png'));


%% Figure 6
%  Outstanding Public Debt

plot_bar( ...
    data.year, ...
    data.ost_pb, ...
    {'Outstanding Public Debt'}, ...
    'Outstanding Public Debt', ...
    'Ratio(%)', ...
    fullfile('figures', 'Figure6.png'));


%% Figure 7
%  Outstanding Debt by Category

plot_line_chart( ...
    data.year, ...
    [data.ost_treasury, ...
     data.ost_lgen, ...
     data.ost_lspe], ...
    {'Outstanding Treasury Debt', ...
     'Outstanding Local General Debt', ...
     'Outstanding Local Special Debt'}, ...
    'Outstanding Public Debt by Category', ...
    'Ratio(%)', ...
    fullfile('figures', 'Figure7.png'));


%% Figure 8
%  Annual Public Debt Principal Repayment

plot_bar( ...
    data.year, ...
    data.ann_pb_principal_repay, ...
    {'Annual Public Debt Principal Repayment'}, ...
    'Annual Public Debt Principal Repayment', ...
    'Ratio(%)', ...
    fullfile('figures', 'Figure8.png'));


%% Figure 9
%  Principal Repayment by Debt Category

plot_line_chart( ...
    data.year, ...
    [data.ann_treasury_principal_repay, ...
     data.ann_lgen_principal_repay, ...
     data.ann_lspe_principal_repay], ...
    {'Treasury', ...
     'Local General Debt', ...
     'Local Special Debt'}, ...
    'Annual Principal Repayment by Debt Category', ...
    'Ratio(%)', ...
    fullfile('figures', 'Figure9.png'));


disp(' ');
disp('All figures have been generated successfully.');
disp('Figures are saved in the "figures" folder.');